### ISSUE TITLE
Add Cross Chain NFT Marketplace tutorial: Part III

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/iota-wiki#1662] opened 2024-08-02 12:36 UTC
**Describe the solution you'd like**
A part III for https://github.com/iotaledger/iota-wiki/issues/1625

**Comment by salaheldinsoliman** [comment] 2024-08-13 09:02
Duplicate of https://github.com/iotaledger/iota-wiki/issues/1663

**Closed by salaheldinsoliman** 2024-08-13 09:02 UTC
Labels: feature
