### ISSUE TITLE
[Task]: Mana Calculator: Check Inputs

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/iota-wiki#1330] opened 2023-11-08 23:52 UTC
We should check inputs for valid inputs.

For example:
- [ ] Performance factor being floats between 0 and 1
- [ ] Stake not being bigger as supply

**Comment by begonaalvarezd** [comment] 2023-11-15 11:20
Duplicate of https://github.com/iotaledger/iota-wiki/issues/1276

**Closed by begonaalvarezd** 2023-11-15 11:20 UTC
